//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZondervanLibrary.Harvester.Counter3SushiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SushiService", ConfigurationName="Counter3SushiService.SushiServiceInterface")]
    public interface SushiServiceInterface {
        
        // CODEGEN: Generating message contract since the operation GetReport is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="SushiService:GetReportIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Organization))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReportResponse))]
        ZondervanLibrary.Harvester.Counter3SushiService.GetReportResponse GetReport(ZondervanLibrary.Harvester.Counter3SushiService.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SushiService:GetReportIn", ReplyAction="*")]
        System.Threading.Tasks.Task<ZondervanLibrary.Harvester.Counter3SushiService.GetReportResponse> GetReportAsync(ZondervanLibrary.Harvester.Counter3SushiService.GetReportRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public partial class ReportRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Requestor requestorField;
        
        private CustomerReference customerReferenceField;
        
        private ReportDefinition reportDefinitionField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Requestor Requestor {
            get {
                return this.requestorField;
            }
            set {
                this.requestorField = value;
                this.RaisePropertyChanged("Requestor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CustomerReference CustomerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
                this.RaisePropertyChanged("CustomerReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReportDefinition ReportDefinition {
            get {
                return this.reportDefinitionField;
            }
            set {
                this.reportDefinitionField = value;
                this.RaisePropertyChanged("ReportDefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
                this.RaisePropertyChanged("CreatedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public partial class Requestor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class PerformanceCounter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MetricType metricTypeField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MetricType MetricType {
            get {
                return this.metricTypeField;
            }
            set {
                this.metricTypeField = value;
                this.RaisePropertyChanged("MetricType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public enum MetricType {
        
        /// <remarks/>
        ft_ps,
        
        /// <remarks/>
        ft_pdf,
        
        /// <remarks/>
        ft_html,
        
        /// <remarks/>
        ft_total,
        
        /// <remarks/>
        Toc,
        
        /// <remarks/>
        @abstract,
        
        /// <remarks/>
        reference,
        
        /// <remarks/>
        data_set,
        
        /// <remarks/>
        audio,
        
        /// <remarks/>
        video,
        
        /// <remarks/>
        image,
        
        /// <remarks/>
        podcast,
        
        /// <remarks/>
        search_reg,
        
        /// <remarks/>
        search_fed,
        
        /// <remarks/>
        session_reg,
        
        /// <remarks/>
        session_fed,
        
        /// <remarks/>
        count,
        
        /// <remarks/>
        other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class DateRange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime beginField;
        
        private System.DateTime endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime Begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
                this.RaisePropertyChanged("Begin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class Metric : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DateRange periodField;
        
        private Category categoryField;
        
        private PerformanceCounter[] instanceField;
        
        private int pubYrField;
        
        private bool pubYrFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DateRange Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
                this.RaisePropertyChanged("Period");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Category Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Instance", Order=2)]
        public PerformanceCounter[] Instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
                this.RaisePropertyChanged("Instance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PubYr {
            get {
                return this.pubYrField;
            }
            set {
                this.pubYrField = value;
                this.RaisePropertyChanged("PubYr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PubYrSpecified {
            get {
                return this.pubYrFieldSpecified;
            }
            set {
                this.pubYrFieldSpecified = value;
                this.RaisePropertyChanged("PubYrSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public enum Category {
        
        /// <remarks/>
        Requests,
        
        /// <remarks/>
        Searches,
        
        /// <remarks/>
        Sessions,
        
        /// <remarks/>
        Turnaways,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class ReportItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Identifier[] itemIdentifierField;
        
        private string itemPlatformField;
        
        private string itemPublisherField;
        
        private string itemNameField;
        
        private DataType itemDataTypeField;
        
        private Metric[] itemPerformanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemIdentifier", Order=0)]
        public Identifier[] ItemIdentifier {
            get {
                return this.itemIdentifierField;
            }
            set {
                this.itemIdentifierField = value;
                this.RaisePropertyChanged("ItemIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemPlatform {
            get {
                return this.itemPlatformField;
            }
            set {
                this.itemPlatformField = value;
                this.RaisePropertyChanged("ItemPlatform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ItemPublisher {
            get {
                return this.itemPublisherField;
            }
            set {
                this.itemPublisherField = value;
                this.RaisePropertyChanged("ItemPublisher");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
                this.RaisePropertyChanged("ItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DataType ItemDataType {
            get {
                return this.itemDataTypeField;
            }
            set {
                this.itemDataTypeField = value;
                this.RaisePropertyChanged("ItemDataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemPerformance", Order=5)]
        public Metric[] ItemPerformance {
            get {
                return this.itemPerformanceField;
            }
            set {
                this.itemPerformanceField = value;
                this.RaisePropertyChanged("ItemPerformance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class Identifier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdentifierType typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentifierType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public enum IdentifierType {
        
        /// <remarks/>
        Online_ISSN,
        
        /// <remarks/>
        Print_ISSN,
        
        /// <remarks/>
        EISSN,
        
        /// <remarks/>
        ISSN,
        
        /// <remarks/>
        ISBN,
        
        /// <remarks/>
        Online_ISBN,
        
        /// <remarks/>
        Print_ISBN,
        
        /// <remarks/>
        DOI,
        
        /// <remarks/>
        Proprietary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public enum DataType {
        
        /// <remarks/>
        Journal,
        
        /// <remarks/>
        Database,
        
        /// <remarks/>
        Platform,
        
        /// <remarks/>
        Book,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class Consortium : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string wellKnownNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WellKnownName {
            get {
                return this.wellKnownNameField;
            }
            set {
                this.wellKnownNameField = value;
                this.RaisePropertyChanged("WellKnownName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class Contact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contact1Field;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contact", Order=0)]
        public string Contact1 {
            get {
                return this.contact1Field;
            }
            set {
                this.contact1Field = value;
                this.RaisePropertyChanged("Contact1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E-mail", Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Vendor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Customer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class Organization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string idField;
        
        private Contact[] contactField;
        
        private string webSiteUrlField;
        
        private string logoUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contact", Order=2)]
        public Contact[] Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=3)]
        public string WebSiteUrl {
            get {
                return this.webSiteUrlField;
            }
            set {
                this.webSiteUrlField = value;
                this.RaisePropertyChanged("WebSiteUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=4)]
        public string LogoUrl {
            get {
                return this.logoUrlField;
            }
            set {
                this.logoUrlField = value;
                this.RaisePropertyChanged("LogoUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class Vendor : Organization {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class Customer : Organization {
        
        private Consortium consortiumField;
        
        private Identifier[] institutionalIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Consortium Consortium {
            get {
                return this.consortiumField;
            }
            set {
                this.consortiumField = value;
                this.RaisePropertyChanged("Consortium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstitutionalIdentifier", Order=1)]
        public Identifier[] InstitutionalIdentifier {
            get {
                return this.institutionalIdentifierField;
            }
            set {
                this.institutionalIdentifierField = value;
                this.RaisePropertyChanged("InstitutionalIdentifier");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/counter")]
    public partial class Report : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Vendor vendorField;
        
        private ReportCustomer[] customerField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private string idField;
        
        private string versionField;
        
        private string nameField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Vendor Vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
                this.RaisePropertyChanged("Vendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Customer", Order=1)]
        public ReportCustomer[] Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
                this.RaisePropertyChanged("CreatedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.niso.org/schemas/counter")]
    public partial class ReportCustomer : Customer {
        
        private ReportItem[] reportItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReportItems", Order=0)]
        public ReportItem[] ReportItems {
            get {
                return this.reportItemsField;
            }
            set {
                this.reportItemsField = value;
                this.RaisePropertyChanged("ReportItems");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public partial class Activity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numberField;
        
        private ExceptionSeverity severityField;
        
        private string messageField;
        
        private string helpUrlField;
        
        private object dataField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExceptionSeverity Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("Severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", IsNullable=true, Order=3)]
        public string HelpUrl {
            get {
                return this.helpUrlField;
            }
            set {
                this.helpUrlField = value;
                this.RaisePropertyChanged("HelpUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public object Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
                this.RaisePropertyChanged("CreatedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public enum ExceptionSeverity {
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Debug,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Fatal,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CounterReportResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public partial class ReportResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Exception[] exceptionField;
        
        private Requestor requestorField;
        
        private CustomerReference customerReferenceField;
        
        private ReportDefinition reportDefinitionField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", IsNullable=true, Order=0)]
        public Exception[] Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Requestor Requestor {
            get {
                return this.requestorField;
            }
            set {
                this.requestorField = value;
                this.RaisePropertyChanged("Requestor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CustomerReference CustomerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
                this.RaisePropertyChanged("CustomerReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ReportDefinition ReportDefinition {
            get {
                return this.reportDefinitionField;
            }
            set {
                this.reportDefinitionField = value;
                this.RaisePropertyChanged("ReportDefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
                this.RaisePropertyChanged("CreatedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public partial class CustomerReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public partial class ReportDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReportDefinitionFilters filtersField;
        
        private string nameField;
        
        private string releaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReportDefinitionFilters Filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
                this.RaisePropertyChanged("Filters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
                this.RaisePropertyChanged("Release");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.niso.org/schemas/sushi")]
    public partial class ReportDefinitionFilters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Range usageDateRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Range UsageDateRange {
            get {
                return this.usageDateRangeField;
            }
            set {
                this.usageDateRangeField = value;
                this.RaisePropertyChanged("UsageDateRange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi")]
    public partial class Range : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime beginField;
        
        private System.DateTime endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime Begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
                this.RaisePropertyChanged("Begin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.niso.org/schemas/sushi/counter")]
    public partial class CounterReportResponse : ReportResponse {
        
        private Report[] reportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://www.niso.org/schemas/counter", IsNullable=false)]
        public Report[] Report {
            get {
                return this.reportField;
            }
            set {
                this.reportField = value;
                this.RaisePropertyChanged("Report");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.niso.org/schemas/sushi/counter", Order=0)]
        public ZondervanLibrary.Harvester.Counter3SushiService.ReportRequest ReportRequest;
        
        public GetReportRequest() {
        }
        
        public GetReportRequest(ZondervanLibrary.Harvester.Counter3SushiService.ReportRequest ReportRequest) {
            this.ReportRequest = ReportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.niso.org/schemas/sushi/counter", Order=0)]
        public ZondervanLibrary.Harvester.Counter3SushiService.CounterReportResponse ReportResponse;
        
        public GetReportResponse() {
        }
        
        public GetReportResponse(ZondervanLibrary.Harvester.Counter3SushiService.CounterReportResponse ReportResponse) {
            this.ReportResponse = ReportResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SushiServiceInterfaceChannel : ZondervanLibrary.Harvester.Counter3SushiService.SushiServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SushiServiceInterfaceClient : System.ServiceModel.ClientBase<ZondervanLibrary.Harvester.Counter3SushiService.SushiServiceInterface>, ZondervanLibrary.Harvester.Counter3SushiService.SushiServiceInterface {
        
        public SushiServiceInterfaceClient() {
        }
        
        public SushiServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SushiServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SushiServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SushiServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZondervanLibrary.Harvester.Counter3SushiService.GetReportResponse ZondervanLibrary.Harvester.Counter3SushiService.SushiServiceInterface.GetReport(ZondervanLibrary.Harvester.Counter3SushiService.GetReportRequest request) {
            return base.Channel.GetReport(request);
        }
        
        public ZondervanLibrary.Harvester.Counter3SushiService.CounterReportResponse GetReport(ZondervanLibrary.Harvester.Counter3SushiService.ReportRequest ReportRequest) {
            ZondervanLibrary.Harvester.Counter3SushiService.GetReportRequest inValue = new ZondervanLibrary.Harvester.Counter3SushiService.GetReportRequest();
            inValue.ReportRequest = ReportRequest;
            ZondervanLibrary.Harvester.Counter3SushiService.GetReportResponse retVal = ((ZondervanLibrary.Harvester.Counter3SushiService.SushiServiceInterface)(this)).GetReport(inValue);
            return retVal.ReportResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZondervanLibrary.Harvester.Counter3SushiService.GetReportResponse> ZondervanLibrary.Harvester.Counter3SushiService.SushiServiceInterface.GetReportAsync(ZondervanLibrary.Harvester.Counter3SushiService.GetReportRequest request) {
            return base.Channel.GetReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZondervanLibrary.Harvester.Counter3SushiService.GetReportResponse> GetReportAsync(ZondervanLibrary.Harvester.Counter3SushiService.ReportRequest ReportRequest) {
            ZondervanLibrary.Harvester.Counter3SushiService.GetReportRequest inValue = new ZondervanLibrary.Harvester.Counter3SushiService.GetReportRequest();
            inValue.ReportRequest = ReportRequest;
            return ((ZondervanLibrary.Harvester.Counter3SushiService.SushiServiceInterface)(this)).GetReportAsync(inValue);
        }
    }
}
