////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.18052
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Schema;
//using System.Xml.Serialization;

//namespace ZondervanLibrary.PatronTranslator.Console.Patrons
//{ // 
//    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
//    // 

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    [System.Xml.Serialization.XmlRootAttribute("oclcPersonas", Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1", IsNullable = false)]
//    public partial class OclcPersonas
//    {

//        [XmlAttribute("schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
//        public string xsiSchemaLocation = "http://worldcat.org/xmlschemas/IDMPersonas-1.1 http://worldcat.org/xmlschemas/IDMPersonas/1.1/IDMPersonas-1.1.xsd";

//        private Persona[] personaField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("persona")]
//        public Persona[] persona
//        {
//            get
//            {
//                return this.personaField;
//            }
//            set
//            {
//                this.personaField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class Persona
//    {
//        private CorrelationInfo[] correlationInfoField;

//        private NameInfo nameInfoField;

//        private System.DateTime dateOfBirthField;

//        private bool dateOfBirthFieldSpecified;

//        private string genderField;

//        private WmsCircPatronInfo wmsCircPatronInfoField;

//        private Preferences preferencesField;

//        private ContactInfo[] contactInfoField;

//        private Role[] roleField;

//        private Relationship[] relationshipField;

//        private Note[] noteField;

//        private KeyValuePair[] additionalInfoField;

//        private OldBarcode[] cancelledBarcodeField;

//        private string oclcUserNameField;

//        private System.DateTime oclcExpirationDateField;

//        private bool oclcExpirationDateFieldSpecified;

//        private string institutionIdField;

//        private string optimisticLockIdField;

//        private string ppidField;

//        private string relyingPartyField;

//        private System.DateTime createdOnField;

//        private bool createdOnFieldSpecified;

//        private string createdByField;

//        private System.DateTime lastUpdatedOnField;

//        private bool lastUpdatedOnFieldSpecified;

//        private string lastUpdatedByField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("correlationInfo")]
//        public CorrelationInfo[] correlationInfo
//        {
//            get
//            {
//                return this.correlationInfoField;
//            }
//            set
//            {
//                this.correlationInfoField = value;
//            }
//        }

//        /// <remarks/>
//        public NameInfo nameInfo
//        {
//            get
//            {
//                return this.nameInfoField;
//            }
//            set
//            {
//                this.nameInfoField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime dateOfBirth
//        {
//            get
//            {
//                return this.dateOfBirthField;
//            }
//            set
//            {
//                this.dateOfBirthField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool dateOfBirthSpecified
//        {
//            get
//            {
//                return this.dateOfBirthFieldSpecified;
//            }
//            set
//            {
//                this.dateOfBirthFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string gender
//        {
//            get
//            {
//                return this.genderField;
//            }
//            set
//            {
//                this.genderField = value;
//            }
//        }

//        /// <remarks/>
//        public WmsCircPatronInfo wmsCircPatronInfo
//        {
//            get
//            {
//                return this.wmsCircPatronInfoField;
//            }
//            set
//            {
//                this.wmsCircPatronInfoField = value;
//            }
//        }

//        /// <remarks/>
//        public Preferences preferences
//        {
//            get
//            {
//                return this.preferencesField;
//            }
//            set
//            {
//                this.preferencesField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("contactInfo")]
//        public ContactInfo[] contactInfo
//        {
//            get
//            {
//                return this.contactInfoField;
//            }
//            set
//            {
//                this.contactInfoField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("role")]
//        public Role[] role
//        {
//            get
//            {
//                return this.roleField;
//            }
//            set
//            {
//                this.roleField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("relationship")]
//        public Relationship[] relationship
//        {
//            get
//            {
//                return this.relationshipField;
//            }
//            set
//            {
//                this.relationshipField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("note")]
//        public Note[] note
//        {
//            get
//            {
//                return this.noteField;
//            }
//            set
//            {
//                this.noteField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("additionalInfo")]
//        public KeyValuePair[] additionalInfo
//        {
//            get
//            {
//                return this.additionalInfoField;
//            }
//            set
//            {
//                this.additionalInfoField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("cancelledBarcode")]
//        public OldBarcode[] cancelledBarcode
//        {
//            get
//            {
//                return this.cancelledBarcodeField;
//            }
//            set
//            {
//                this.cancelledBarcodeField = value;
//            }
//        }

//        /// <remarks/>
//        public string oclcUserName
//        {
//            get
//            {
//                return this.oclcUserNameField;
//            }
//            set
//            {
//                this.oclcUserNameField = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime oclcExpirationDate
//        {
//            get
//            {
//                return this.oclcExpirationDateField;
//            }
//            set
//            {
//                this.oclcExpirationDateField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool oclcExpirationDateSpecified
//        {
//            get
//            {
//                return this.oclcExpirationDateFieldSpecified;
//            }
//            set
//            {
//                this.oclcExpirationDateFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string institutionId
//        {
//            get
//            {
//                return this.institutionIdField;
//            }
//            set
//            {
//                this.institutionIdField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string optimisticLockId
//        {
//            get
//            {
//                return this.optimisticLockIdField;
//            }
//            set
//            {
//                this.optimisticLockIdField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string ppid
//        {
//            get
//            {
//                return this.ppidField;
//            }
//            set
//            {
//                this.ppidField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string relyingParty
//        {
//            get
//            {
//                return this.relyingPartyField;
//            }
//            set
//            {
//                this.relyingPartyField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public System.DateTime createdOn
//        {
//            get
//            {
//                return this.createdOnField;
//            }
//            set
//            {
//                this.createdOnField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool createdOnSpecified
//        {
//            get
//            {
//                return this.createdOnFieldSpecified;
//            }
//            set
//            {
//                this.createdOnFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string createdBy
//        {
//            get
//            {
//                return this.createdByField;
//            }
//            set
//            {
//                this.createdByField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public System.DateTime lastUpdatedOn
//        {
//            get
//            {
//                return this.lastUpdatedOnField;
//            }
//            set
//            {
//                this.lastUpdatedOnField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool lastUpdatedOnSpecified
//        {
//            get
//            {
//                return this.lastUpdatedOnFieldSpecified;
//            }
//            set
//            {
//                this.lastUpdatedOnFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string lastUpdatedBy
//        {
//            get
//            {
//                return this.lastUpdatedByField;
//            }
//            set
//            {
//                this.lastUpdatedByField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class CorrelationInfo
//    {
//        private string sourceSystemField;

//        private string idAtSourceField;

//        private System.DateTime lastLoginDateField;

//        private bool lastLoginDateFieldSpecified;

//        private bool isBlockedField;

//        private bool isBlockedFieldSpecified;

//        private string idField;

//        /// <remarks/>
//        public string sourceSystem
//        {
//            get
//            {
//                return this.sourceSystemField;
//            }
//            set
//            {
//                this.sourceSystemField = value;
//            }
//        }

//        /// <remarks/>
//        public string idAtSource
//        {
//            get
//            {
//                return this.idAtSourceField;
//            }
//            set
//            {
//                this.idAtSourceField = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime lastLoginDate
//        {
//            get
//            {
//                return this.lastLoginDateField;
//            }
//            set
//            {
//                this.lastLoginDateField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool lastLoginDateSpecified
//        {
//            get
//            {
//                return this.lastLoginDateFieldSpecified;
//            }
//            set
//            {
//                this.lastLoginDateFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public bool isBlocked
//        {
//            get
//            {
//                return this.isBlockedField;
//            }
//            set
//            {
//                this.isBlockedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isBlockedSpecified
//        {
//            get
//            {
//                return this.isBlockedFieldSpecified;
//            }
//            set
//            {
//                this.isBlockedFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id
//        {
//            get
//            {
//                return this.idField;
//            }
//            set
//            {
//                this.idField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class OldBarcode
//    {

//        private string barcodeField;

//        private System.DateTime cancelledOnField;

//        /// <remarks/>
//        public string barcode
//        {
//            get
//            {
//                return this.barcodeField;
//            }
//            set
//            {
//                this.barcodeField = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime cancelledOn
//        {
//            get
//            {
//                return this.cancelledOnField;
//            }
//            set
//            {
//                this.cancelledOnField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class KeyValuePair
//    {

//        private string businessContextField;

//        private string keyField;

//        private string valueField;

//        private string idField;

//        /// <remarks/>
//        public string businessContext
//        {
//            get
//            {
//                return this.businessContextField;
//            }
//            set
//            {
//                this.businessContextField = value;
//            }
//        }

//        /// <remarks/>
//        public string key
//        {
//            get
//            {
//                return this.keyField;
//            }
//            set
//            {
//                this.keyField = value;
//            }
//        }

//        /// <remarks/>
//        public string value
//        {
//            get
//            {
//                return this.valueField;
//            }
//            set
//            {
//                this.valueField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id
//        {
//            get
//            {
//                return this.idField;
//            }
//            set
//            {
//                this.idField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class Note
//    {

//        private string businessContextField;

//        private string authorIdField;

//        private string flagField;

//        private bool isPublicField;

//        private bool isPublicFieldSpecified;

//        private System.DateTime modifiedDateField;

//        private bool modifiedDateFieldSpecified;

//        private string textField;

//        private string idField;

//        /// <remarks/>
//        public string businessContext
//        {
//            get
//            {
//                return this.businessContextField;
//            }
//            set
//            {
//                this.businessContextField = value;
//            }
//        }

//        /// <remarks/>
//        public string authorId
//        {
//            get
//            {
//                return this.authorIdField;
//            }
//            set
//            {
//                this.authorIdField = value;
//            }
//        }

//        /// <remarks/>
//        public string flag
//        {
//            get
//            {
//                return this.flagField;
//            }
//            set
//            {
//                this.flagField = value;
//            }
//        }

//        /// <remarks/>
//        public bool isPublic
//        {
//            get
//            {
//                return this.isPublicField;
//            }
//            set
//            {
//                this.isPublicField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isPublicSpecified
//        {
//            get
//            {
//                return this.isPublicFieldSpecified;
//            }
//            set
//            {
//                this.isPublicFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime modifiedDate
//        {
//            get
//            {
//                return this.modifiedDateField;
//            }
//            set
//            {
//                this.modifiedDateField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool modifiedDateSpecified
//        {
//            get
//            {
//                return this.modifiedDateFieldSpecified;
//            }
//            set
//            {
//                this.modifiedDateFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string text
//        {
//            get
//            {
//                return this.textField;
//            }
//            set
//            {
//                this.textField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id
//        {
//            get
//            {
//                return this.idField;
//            }
//            set
//            {
//                this.idField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class Relationship
//    {

//        private string relationshipTypeField;

//        private string targetUserIdField;

//        private string idField;

//        /// <remarks/>
//        public string relationshipType
//        {
//            get
//            {
//                return this.relationshipTypeField;
//            }
//            set
//            {
//                this.relationshipTypeField = value;
//            }
//        }

//        /// <remarks/>
//        public string targetUserId
//        {
//            get
//            {
//                return this.targetUserIdField;
//            }
//            set
//            {
//                this.targetUserIdField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id
//        {
//            get
//            {
//                return this.idField;
//            }
//            set
//            {
//                this.idField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class Role
//    {

//        private string authorityIdField;

//        private string authorityIdTypeField;

//        private bool isExplicitField;

//        private bool isExplicitFieldSpecified;

//        private string roleNameField;

//        private string idField;

//        /// <remarks/>
//        public string authorityId
//        {
//            get
//            {
//                return this.authorityIdField;
//            }
//            set
//            {
//                this.authorityIdField = value;
//            }
//        }

//        /// <remarks/>
//        public string authorityIdType
//        {
//            get
//            {
//                return this.authorityIdTypeField;
//            }
//            set
//            {
//                this.authorityIdTypeField = value;
//            }
//        }

//        /// <remarks/>
//        public bool isExplicit
//        {
//            get
//            {
//                return this.isExplicitField;
//            }
//            set
//            {
//                this.isExplicitField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isExplicitSpecified
//        {
//            get
//            {
//                return this.isExplicitFieldSpecified;
//            }
//            set
//            {
//                this.isExplicitFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string roleName
//        {
//            get
//            {
//                return this.roleNameField;
//            }
//            set
//            {
//                this.roleNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id
//        {
//            get
//            {
//                return this.idField;
//            }
//            set
//            {
//                this.idField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class EmailAddress
//    {

//        private string emailAddressField;

//        private bool isValidField;

//        private bool isValidFieldSpecified;

//        private System.DateTime verifiedField;

//        private bool verifiedFieldSpecified;

//        private bool isPrimaryField;

//        private bool isPrimaryFieldSpecified;

//        /// <remarks/>
//        public string emailAddress
//        {
//            get
//            {
//                return this.emailAddressField;
//            }
//            set
//            {
//                this.emailAddressField = value;
//            }
//        }

//        /// <remarks/>
//        public bool isValid
//        {
//            get
//            {
//                return this.isValidField;
//            }
//            set
//            {
//                this.isValidField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isValidSpecified
//        {
//            get
//            {
//                return this.isValidFieldSpecified;
//            }
//            set
//            {
//                this.isValidFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime verified
//        {
//            get
//            {
//                return this.verifiedField;
//            }
//            set
//            {
//                this.verifiedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool verifiedSpecified
//        {
//            get
//            {
//                return this.verifiedFieldSpecified;
//            }
//            set
//            {
//                this.verifiedFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public bool isPrimary
//        {
//            get
//            {
//                return this.isPrimaryField;
//            }
//            set
//            {
//                this.isPrimaryField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isPrimarySpecified
//        {
//            get
//            {
//                return this.isPrimaryFieldSpecified;
//            }
//            set
//            {
//                this.isPrimaryFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class Phone
//    {

//        private string numberField;

//        private bool isValidField;

//        private bool isValidFieldSpecified;

//        private System.DateTime verifiedField;

//        private bool verifiedFieldSpecified;

//        private bool isPrimaryField;

//        private bool isPrimaryFieldSpecified;

//        /// <remarks/>
//        public string number
//        {
//            get
//            {
//                return this.numberField;
//            }
//            set
//            {
//                this.numberField = value;
//            }
//        }

//        /// <remarks/>
//        public bool isValid
//        {
//            get
//            {
//                return this.isValidField;
//            }
//            set
//            {
//                this.isValidField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isValidSpecified
//        {
//            get
//            {
//                return this.isValidFieldSpecified;
//            }
//            set
//            {
//                this.isValidFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime verified
//        {
//            get
//            {
//                return this.verifiedField;
//            }
//            set
//            {
//                this.verifiedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool verifiedSpecified
//        {
//            get
//            {
//                return this.verifiedFieldSpecified;
//            }
//            set
//            {
//                this.verifiedFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public bool isPrimary
//        {
//            get
//            {
//                return this.isPrimaryField;
//            }
//            set
//            {
//                this.isPrimaryField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isPrimarySpecified
//        {
//            get
//            {
//                return this.isPrimaryFieldSpecified;
//            }
//            set
//            {
//                this.isPrimaryFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class PostalAddress
//    {

//        private string streetAddressLine1Field;

//        private string streetAddressLine2Field;

//        private string cityOrLocalityField;

//        private string stateOrProvinceField;

//        private string postalCodeField;

//        private string countryField;

//        private bool isValidField;

//        private bool isValidFieldSpecified;

//        private System.DateTime verifiedField;

//        private bool verifiedFieldSpecified;

//        /// <remarks/>
//        public string streetAddressLine1
//        {
//            get
//            {
//                return this.streetAddressLine1Field;
//            }
//            set
//            {
//                this.streetAddressLine1Field = value;
//            }
//        }

//        /// <remarks/>
//        /// 
//        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
//        public string streetAddressLine2
//        {
//            get
//            {
//                return this.streetAddressLine2Field;
//            }
//            set
//            {
//                this.streetAddressLine2Field = value;
//            }
//        }

//        /// <remarks/>
//        public string cityOrLocality
//        {
//            get
//            {
//                return this.cityOrLocalityField;
//            }
//            set
//            {
//                this.cityOrLocalityField = value;
//            }
//        }

//        /// <remarks/>
//        public string stateOrProvince
//        {
//            get
//            {
//                return this.stateOrProvinceField;
//            }
//            set
//            {
//                this.stateOrProvinceField = value;
//            }
//        }

//        /// <remarks/>
//        public string postalCode
//        {
//            get
//            {
//                return this.postalCodeField;
//            }
//            set
//            {
//                this.postalCodeField = value;
//            }
//        }

//        /// <remarks/>
//        public string country
//        {
//            get
//            {
//                return this.countryField;
//            }
//            set
//            {
//                this.countryField = value;
//            }
//        }

//        /// <remarks/>
//        public bool isValid
//        {
//            get
//            {
//                return this.isValidField;
//            }
//            set
//            {
//                this.isValidField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isValidSpecified
//        {
//            get
//            {
//                return this.isValidFieldSpecified;
//            }
//            set
//            {
//                this.isValidFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime verified
//        {
//            get
//            {
//                return this.verifiedField;
//            }
//            set
//            {
//                this.verifiedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool verifiedSpecified
//        {
//            get
//            {
//                return this.verifiedFieldSpecified;
//            }
//            set
//            {
//                this.verifiedFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class PhysicalLocation
//    {

//        private PostalAddress postalAddressField;

//        private Phone[] phoneField;

//        private bool isPermanentField;

//        private bool isPermanentFieldSpecified;

//        private System.DateTime validFromField;

//        private bool validFromFieldSpecified;

//        private System.DateTime validToField;

//        private bool validToFieldSpecified;

//        private string labelField;

//        private bool isPrimaryField;

//        private bool isPrimaryFieldSpecified;

//        /// <remarks/>
//        public PostalAddress postalAddress
//        {
//            get
//            {
//                return this.postalAddressField;
//            }
//            set
//            {
//                this.postalAddressField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("phone")]
//        public Phone[] phone
//        {
//            get
//            {
//                return this.phoneField;
//            }
//            set
//            {
//                this.phoneField = value;
//            }
//        }

//        /// <remarks/>
//        public bool isPermanent
//        {
//            get
//            {
//                return this.isPermanentField;
//            }
//            set
//            {
//                this.isPermanentField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isPermanentSpecified
//        {
//            get
//            {
//                return this.isPermanentFieldSpecified;
//            }
//            set
//            {
//                this.isPermanentFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime validFrom
//        {
//            get
//            {
//                return this.validFromField;
//            }
//            set
//            {
//                this.validFromField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool validFromSpecified
//        {
//            get
//            {
//                return this.validFromFieldSpecified;
//            }
//            set
//            {
//                this.validFromFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime validTo
//        {
//            get
//            {
//                return this.validToField;
//            }
//            set
//            {
//                this.validToField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool validToSpecified
//        {
//            get
//            {
//                return this.validToFieldSpecified;
//            }
//            set
//            {
//                this.validToFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string label
//        {
//            get
//            {
//                return this.labelField;
//            }
//            set
//            {
//                this.labelField = value;
//            }
//        }

//        /// <remarks/>
//        public bool isPrimary
//        {
//            get
//            {
//                return this.isPrimaryField;
//            }
//            set
//            {
//                this.isPrimaryField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isPrimarySpecified
//        {
//            get
//            {
//                return this.isPrimaryFieldSpecified;
//            }
//            set
//            {
//                this.isPrimaryFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class ContactInfo
//    {

//        private object itemField;

//        private string idField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("email", typeof(EmailAddress))]
//        [System.Xml.Serialization.XmlElementAttribute("phone", typeof(Phone))]
//        [System.Xml.Serialization.XmlElementAttribute("physicalLocation", typeof(PhysicalLocation))]
//        public object Item
//        {
//            get
//            {
//                return this.itemField;
//            }
//            set
//            {
//                this.itemField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id
//        {
//            get
//            {
//                return this.idField;
//            }
//            set
//            {
//                this.idField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class NotificationMethod
//    {

//        private string labelField;

//        private string businessContextField;

//        /// <remarks/>
//        public string label
//        {
//            get
//            {
//                return this.labelField;
//            }
//            set
//            {
//                this.labelField = value;
//            }
//        }

//        /// <remarks/>
//        public string businessContext
//        {
//            get
//            {
//                return this.businessContextField;
//            }
//            set
//            {
//                this.businessContextField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class Preferences
//    {

//        private string localeField;

//        private bool noTelephoneCallsField;

//        private bool noTelephoneCallsFieldSpecified;

//        private NotificationMethod preferredNotificationMethodField;

//        private string timezoneField;

//        private bool useHighContrastDisplayField;

//        private bool useHighContrastDisplayFieldSpecified;

//        /// <remarks/>
//        public string locale
//        {
//            get
//            {
//                return this.localeField;
//            }
//            set
//            {
//                this.localeField = value;
//            }
//        }

//        /// <remarks/>
//        public bool noTelephoneCalls
//        {
//            get
//            {
//                return this.noTelephoneCallsField;
//            }
//            set
//            {
//                this.noTelephoneCallsField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool noTelephoneCallsSpecified
//        {
//            get
//            {
//                return this.noTelephoneCallsFieldSpecified;
//            }
//            set
//            {
//                this.noTelephoneCallsFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public NotificationMethod preferredNotificationMethod
//        {
//            get
//            {
//                return this.preferredNotificationMethodField;
//            }
//            set
//            {
//                this.preferredNotificationMethodField = value;
//            }
//        }

//        /// <remarks/>
//        public string timezone
//        {
//            get
//            {
//                return this.timezoneField;
//            }
//            set
//            {
//                this.timezoneField = value;
//            }
//        }

//        /// <remarks/>
//        public bool useHighContrastDisplay
//        {
//            get
//            {
//                return this.useHighContrastDisplayField;
//            }
//            set
//            {
//                this.useHighContrastDisplayField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool useHighContrastDisplaySpecified
//        {
//            get
//            {
//                return this.useHighContrastDisplayFieldSpecified;
//            }
//            set
//            {
//                this.useHighContrastDisplayFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class WmsCircPatronInfo
//    {

//        private string barcodeField;

//        private string barcodeStatusField;

//        private string pinField;

//        private string borrowerCategoryField;

//        private System.DateTime circRegistrationDateField;

//        private bool circRegistrationDateFieldSpecified;

//        private System.DateTime circExpirationDateField;

//        private bool circExpirationDateFieldSpecified;

//        private string homeBranchField;

//        private bool isCircBlockedField;

//        private bool isCircBlockedFieldSpecified;

//        private bool isCollectionExemptField;

//        private bool isCollectionExemptFieldSpecified;

//        private bool isFineExemptField;

//        private bool isFineExemptFieldSpecified;

//        private bool isVerifiedField;

//        private bool isVerifiedFieldSpecified;

//        private bool storeCheckoutHistoryField;

//        private bool storeCheckoutHistoryFieldSpecified;

//        private string claimedLostCountField;

//        private string claimedReturnedCountField;

//        private string claimedNeverHadCountField;

//        private decimal waivedAmountField;

//        private bool waivedAmountFieldSpecified;

//        /// <remarks/>
//        public string barcode
//        {
//            get
//            {
//                return this.barcodeField;
//            }
//            set
//            {
//                this.barcodeField = value;
//            }
//        }

//        /// <remarks/>
//        public string barcodeStatus
//        {
//            get
//            {
//                return this.barcodeStatusField;
//            }
//            set
//            {
//                this.barcodeStatusField = value;
//            }
//        }

//        /// <remarks/>
//        public string pin
//        {
//            get
//            {
//                return this.pinField;
//            }
//            set
//            {
//                this.pinField = value;
//            }
//        }

//        /// <remarks/>
//        public string borrowerCategory
//        {
//            get
//            {
//                return this.borrowerCategoryField;
//            }
//            set
//            {
//                this.borrowerCategoryField = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime circRegistrationDate
//        {
//            get
//            {
//                return this.circRegistrationDateField;
//            }
//            set
//            {
//                this.circRegistrationDateField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool circRegistrationDateSpecified
//        {
//            get
//            {
//                return this.circRegistrationDateFieldSpecified;
//            }
//            set
//            {
//                this.circRegistrationDateFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime circExpirationDate
//        {
//            get
//            {
//                return this.circExpirationDateField;
//            }
//            set
//            {
//                this.circExpirationDateField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool circExpirationDateSpecified
//        {
//            get
//            {
//                return this.circExpirationDateFieldSpecified;
//            }
//            set
//            {
//                this.circExpirationDateFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string homeBranch
//        {
//            get
//            {
//                return this.homeBranchField;
//            }
//            set
//            {
//                this.homeBranchField = value;
//            }
//        }

//        /// <remarks/>
//        public bool isCircBlocked
//        {
//            get
//            {
//                return this.isCircBlockedField;
//            }
//            set
//            {
//                this.isCircBlockedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isCircBlockedSpecified
//        {
//            get
//            {
//                return this.isCircBlockedFieldSpecified;
//            }
//            set
//            {
//                this.isCircBlockedFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public bool isCollectionExempt
//        {
//            get
//            {
//                return this.isCollectionExemptField;
//            }
//            set
//            {
//                this.isCollectionExemptField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isCollectionExemptSpecified
//        {
//            get
//            {
//                return this.isCollectionExemptFieldSpecified;
//            }
//            set
//            {
//                this.isCollectionExemptFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public bool isFineExempt
//        {
//            get
//            {
//                return this.isFineExemptField;
//            }
//            set
//            {
//                this.isFineExemptField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isFineExemptSpecified
//        {
//            get
//            {
//                return this.isFineExemptFieldSpecified;
//            }
//            set
//            {
//                this.isFineExemptFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public bool isVerified
//        {
//            get
//            {
//                return this.isVerifiedField;
//            }
//            set
//            {
//                this.isVerifiedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool isVerifiedSpecified
//        {
//            get
//            {
//                return this.isVerifiedFieldSpecified;
//            }
//            set
//            {
//                this.isVerifiedFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public bool storeCheckoutHistory
//        {
//            get
//            {
//                return this.storeCheckoutHistoryField;
//            }
//            set
//            {
//                this.storeCheckoutHistoryField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool storeCheckoutHistorySpecified
//        {
//            get
//            {
//                return this.storeCheckoutHistoryFieldSpecified;
//            }
//            set
//            {
//                this.storeCheckoutHistoryFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
//        public string claimedLostCount
//        {
//            get
//            {
//                return this.claimedLostCountField;
//            }
//            set
//            {
//                this.claimedLostCountField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
//        public string claimedReturnedCount
//        {
//            get
//            {
//                return this.claimedReturnedCountField;
//            }
//            set
//            {
//                this.claimedReturnedCountField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
//        public string claimedNeverHadCount
//        {
//            get
//            {
//                return this.claimedNeverHadCountField;
//            }
//            set
//            {
//                this.claimedNeverHadCountField = value;
//            }
//        }

//        /// <remarks/>
//        public decimal waivedAmount
//        {
//            get
//            {
//                return this.waivedAmountField;
//            }
//            set
//            {
//                this.waivedAmountField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool waivedAmountSpecified
//        {
//            get
//            {
//                return this.waivedAmountFieldSpecified;
//            }
//            set
//            {
//                this.waivedAmountFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://worldcat.org/xmlschemas/IDMPersonas-1.1")]
//    public partial class NameInfo
//    {

//        private string prefixField;

//        private string givenNameField;

//        private string middleNameField;

//        private string familyNameField;

//        private string suffixField;

//        private string fullNameField;

//        private string nicknameField;

//        private string[] otherNameInfoField;

//        /// <remarks/>
//        public string prefix
//        {
//            get
//            {
//                return this.prefixField;
//            }
//            set
//            {
//                this.prefixField = value;
//            }
//        }

//        /// <remarks/>
//        public string givenName
//        {
//            get
//            {
//                return this.givenNameField;
//            }
//            set
//            {
//                this.givenNameField = value;
//            }
//        }

//        /// <remarks/>
//        public string middleName
//        {
//            get
//            {
//                return this.middleNameField;
//            }
//            set
//            {
//                this.middleNameField = value;
//            }
//        }

//        /// <remarks/>
//        public string familyName
//        {
//            get
//            {
//                return this.familyNameField;
//            }
//            set
//            {
//                this.familyNameField = value;
//            }
//        }

//        /// <remarks/>
//        public string suffix
//        {
//            get
//            {
//                return this.suffixField;
//            }
//            set
//            {
//                this.suffixField = value;
//            }
//        }

//        /// <remarks/>
//        public string fullName
//        {
//            get
//            {
//                return this.fullNameField;
//            }
//            set
//            {
//                this.fullNameField = value;
//            }
//        }

//        /// <remarks/>
//        public string nickname
//        {
//            get
//            {
//                return this.nicknameField;
//            }
//            set
//            {
//                this.nicknameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("otherNameInfo")]
//        public string[] otherNameInfo
//        {
//            get
//            {
//                return this.otherNameInfoField;
//            }
//            set
//            {
//                this.otherNameInfoField = value;
//            }
//        }
//    }
//}